### ISSUE TITLE
Список созданных ваканчии у работодателя

### ISSUE THREAD

**Issue by Alnazhm** [Nadezhda2205/homework_68#12]
### Список созданных вакансий. 
На главной странице профиля (Данные вакансии должны быть видны только владельцу профиля) выводятся созданные вакансии в виде небольших табличек, с базовой информацией : название вакансии, дата обновления вакансии. Также в данных карточках должна быть кнопка обновить и редактировать.

**Comment by Nadezhda2205** [comment]
Логика реализована в детальном просмотре работодателя.
