### ISSUE TITLE
Создание вакансии

### ISSUE THREAD

**Issue by Alnazhm** [Nadezhda2205/homework_68#13]
### Возможность создания вакансии. 
Ниже приведен пример разделения и основные модули для вакансии.

1. Название вакансии
2. Заработная плата
3. Детальное описание вакансии включающее в себя требования по знаниям соискателя.
4. Указание требуемого опыта работы от и до (лет)
5. Категория вакансии, выбирается из выпадающего списка.

**Comment by Nadezhda2205** [comment]
Затраченное время: 30 минут
