### ISSUE TITLE
Реализация основного фунционала работодателя

### ISSUE THREAD

**Issue by Alnazhm** [Nadezhda2205/homework_68#17]
1. У работодателя в специальном разделе 
2. также должен быть список откликов на каждую из вакансий с возможностью перехода к непосредственному пользователю.
3.  Список вакансий, можно фильтровать по категориям, а так же сортировать по зарплате и осуществлять их поиск по названию. (Бонус +0,5 балла реализовать live search с помощью Ajax для поиска вакансий) 
4. На странице со списком вакансий должно отображаться не более 20 вакансий, остальные должны располагаться на следующих страницах. 
5. Соответственно у вас должна быть реализована постраничная навигация.
6. Со стороны работодателя так же добавить возможность просмотра резюме соискателей по категориям. с дополнительной возможностью открытия чата с выбранным соискателем. 
7. При открытии чата с соискателем обязателен выбор вакансии по поводу которой идет обсуждение.

**Comment by Nadezhda2205** [comment]
выполнено
