### ISSUE TITLE
Детальный просмотр аккаунта (работодателя/соискателя)

### ISSUE THREAD

**Issue by Nadezhda2205** [Nadezhda2205/homework_68#25]
Создание AccountDetailView(DetailView) для обработки запроса детального просмотра аккаунта (компании/соискателя).
Для дальнейшей логики отображения детальной страницы компании и соискателя.

**Comment by Nadezhda2205** [comment]
Создан AccountDetailView(DetailView) для обработки запроса детального просмотра аккаунта (работодателя/соискателя).
Для дальнейшей логики отображения детальной страницы компании и соискателя. Отработана логика проверки (работодателя/соискателя). 

Отработана страница детального просмотра работодателя detail_employer.html
Добавлен пустой шаблон detail_applicant.html


### Отработать страницу детального просмотра соискателя

**Comment by Alnazhm** [comment]
Сделано
