### ISSUE TITLE
Создать структуру базы данных и структуру проекта

### ISSUE THREAD

**Issue by Nadezhda2205** [Nadezhda2205/homework_68#4]
Что сделать:
Схематично изобразить структуру базы данных. Таблицы, поля, типы данных, связи. 
[https://lucid.app/lucidchart/0b5b2f3f-0444-4a48-bd97-5fafe8c3589b/edit?invitationId=inv_2ee79a9d-2c20-4867-867c-9765d03adb70&page=0_0#](url)

Планируемое время :  2 часа

**Comment by Alnazhm** [comment]
Создание структуры базы данных и структуру проекта в работе и соответственно регистрация авторизация пользователей

**Comment by Alnazhm** [comment]
Сделали структуру данных пока так, если нужно будет еще изменить изменим походу проекта.
